### ISSUE TITLE
Doesn't properly support Composition & Dependencies

### ISSUE THREAD

**Issue by goodguyry** [alleyinteractive/css-modules-helpers#2]
When composing a class, the composed classname is added to the JSON mapping. Because it's one string, the helper functions aren't properly formatting the return values.

I noticed this just now with `getComponentSelectors`, but I'm sure the others are affected by this oversight as well.

Given the following:

```css
/* theme.css */
.btn {
  border: 1px solid;
  color: red;
}
```

```css
/* header.css */
.wrapper {
  composes: btn from 'theme.css';
}
```

```json
{"header":{"wrapper":"header__wrapper___2JY86 theme__btn___2TPiI"}}
```

The output from `getComponentSelectors`

```javascript
const selectors = getComponentSelectors('header');
// '.header__wrapper___2JY86 theme__btn___2TPiI'
```
